#!/usr/bin/env python3
"""Refuse hand-drawn icons in shell UI code.

Owner rule (2026-09-03): UI icons are never hand-drawn. Every shell takes them from one
open-source library -- Tabler Icons (MIT), vendored under assets/icons/tabler/ -- through
tools/gen_icons.py. A glyph typed out as a bezier in a view controller drifts from the other
three shells the moment anyone touches it, and nobody notices until the icons no longer match.

What this refuses:
  * UIBezierPath / CGPath / CGContextAddCurve glyph drawing in iOS and iOS-kiosk view files
  * <path android:pathData> in an Android drawable that gen_icons.py did not write
  * Path Data= or <Geometry> literals in XAML outside the generated Icons.xaml
  * inline <svg><path d=...> in webui outside the generated sprite

Shapes that are not icons -- a progress ring, a waveform, a slide-to-trigger track -- are real
and are listed in ALLOWED below, with the reason. Add to that list deliberately, not to make a
red build go away.

Comments are stripped before anything is matched. A doc comment that says "this used to be drawn
with UIBezierPath and is a template image now" is a record of the rule being followed, and
flagging it would teach people to stop writing that sentence.

  python3 tools/check_icons.py            check the whole tree
  python3 tools/check_icons.py --base REF  check only files changed since REF
"""

import argparse
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Paths that legitimately draw a shape that is not an icon. Each entry is (path, reason).
ALLOWED = [
    ("win/DoorbellApp/Resources/Icons.xaml", "the generated Tabler geometry dictionary"),
    ("webui/icons/tabler-sprite.svg", "the generated Tabler sprite"),
    ("webui/admin/index.html", "carries the generated sprite between its markers"),
    ("android/app/src/main/res/drawable/banner_tv.xml",
     "the Android TV launcher banner: artwork with a title, not a UI icon"),
]

GENERATED_MARKER = "Generated by tools/gen_icons.py"

IOS_PATTERNS = [
    (re.compile(r"\bUIBezierPath\b"), "UIBezierPath glyph drawing"),
    (re.compile(r"\bCGPathAdd(?:Curve|QuadCurve|Arc)\w*\b"), "CGPath glyph drawing"),
    (re.compile(r"\bCGContextAdd(?:Curve|QuadCurve|Arc)\w*\b"), "CGContext glyph drawing"),
    (re.compile(r"\bPath\s*\{"), "SwiftUI Path glyph drawing"),
]
ANDROID_PATTERN = re.compile(r"<path[^>]*android:pathData")
XAML_PATTERNS = [
    (re.compile(r"\bData\s*=\s*\"[MmLlCcQqAaZzHhVv][\s\d.,-]"), "inline XAML path geometry"),
    (re.compile(r"<(?:Path|Stream)?Geometry\b"), "inline XAML geometry"),
]
WEB_PATTERN = re.compile(r"<svg\b[^>]*>.*?<path\b[^>]*\bd\s*=", re.S)

IOS_DIRS = ("ios/", "ios-kiosk/", "ios-legacy/")
WEB_DIRS = ("webui/",)


def allowed(rel):
    for path, _reason in ALLOWED:
        if rel == path or rel.startswith(path.rstrip("/") + "/"):
            return True
    return False


def is_view_file(rel):
    if not rel.startswith(IOS_DIRS):
        return False
    return rel.endswith((".m", ".mm", ".swift", ".h"))


def changed_files(base):
    try:
        out = subprocess.check_output(["git", "diff", "--name-only", base + "...HEAD"],
                                      cwd=ROOT, stderr=subprocess.DEVNULL)
    except (subprocess.CalledProcessError, OSError):
        return None
    return [line for line in out.decode("utf-8").splitlines() if line]


def all_files():
    out = subprocess.check_output(["git", "ls-files"], cwd=ROOT)
    return [line for line in out.decode("utf-8").splitlines() if line]


C_FAMILY_SUFFIXES = (".m", ".mm", ".swift", ".h", ".js", ".css")
MARKUP_SUFFIXES = (".xml", ".xaml", ".html", ".htm", ".svg")
HASH_SUFFIXES = (".py", ".sh", ".yml", ".yaml")


def strip_comments(text, rel):
    """Blank out comment bodies, leaving every other character at its original offset.

    Offsets are preserved rather than the comments deleted, so a line number counted in the
    result still points at the line it does in the file. Which comment syntax applies is decided
    by extension: "//" is only a comment in the C family, because in markup it is the middle of
    every http:// URL, and "#" is only a comment where "#RRGGBB" is not a colour.
    """
    chars = list(text)
    length = len(text)
    lower_name = rel.lower()

    def blank(start, end):
        for index in range(start, min(end, length)):
            if chars[index] != "\n":
                chars[index] = " "

    # In a view file a string literal is prose, never drawing code, so its contents are blanked
    # as well -- "removed the UIBezierPath" in a log line is not a finding. Script and style
    # files are different: webui builds real SVG markup inside string literals, and blanking
    # those would hide an icon typed out there by hand, which is the very thing being looked for.
    blank_strings = lower_name.endswith((".m", ".mm", ".swift", ".h"))

    def skip_quoted(index, quote):
        start = index
        index += 1
        while index < length:
            if text[index] == "\\":
                index += 2
                continue
            if text[index] == quote or text[index] == "\n":
                index += 1
                break
            index += 1
        if blank_strings:
            blank(start, index)
        return index

    def blank_pair(opener, closer):
        index = text.find(opener)
        while index >= 0:
            end = text.find(closer, index + len(opener))
            end = length if end < 0 else end + len(closer)
            blank(index, end)
            index = text.find(opener, end)

    if lower_name.endswith(C_FAMILY_SUFFIXES):
        index = 0
        while index < length:
            char = text[index]
            if char in "\"'":
                index = skip_quoted(index, char)
                continue
            if char == "/" and index + 1 < length:
                following = text[index + 1]
                if following == "/":
                    end = text.find("\n", index)
                    end = length if end < 0 else end
                    blank(index, end)
                    index = end
                    continue
                if following == "*":
                    end = text.find("*/", index + 2)
                    end = length if end < 0 else end + 2
                    blank(index, end)
                    index = end
                    continue
            index += 1
    elif lower_name.endswith(MARKUP_SUFFIXES):
        blank_pair("<!--", "-->")
        # Style blocks inside a page use C-style comments; URLs make "//" unsafe here.
        blank_pair("/*", "*/")
    elif lower_name.endswith(HASH_SUFFIXES):
        index = 0
        while index < length:
            char = text[index]
            if char in "\"'":
                index = skip_quoted(index, char)
                continue
            if char == "#":
                end = text.find("\n", index)
                end = length if end < 0 else end
                blank(index, end)
                index = end
                continue
            index += 1
    return "".join(chars)


def read(rel):
    """File contents, or None when the file is binary or unreadable.

    A path that does not exist is a caller error, not an empty file: a test that names a file
    the tree no longer has would otherwise pass by finding nothing in it.
    """
    path = os.path.join(ROOT, rel)
    if not os.path.isfile(path):
        raise FileNotFoundError(path)
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read()
    except (UnicodeDecodeError, OSError):
        return None


def violations_in(rel):
    """Findings for one existing file. Raises FileNotFoundError if the path is not there."""
    text = read(rel)
    if allowed(rel):
        return []
    if text is None:
        return []
    # The marker lives in a comment, so it is looked for before the comments are stripped.
    if GENERATED_MARKER in text:
        return []
    text = strip_comments(text, rel)
    found = []
    if is_view_file(rel):
        for pattern, what in IOS_PATTERNS:
            match = pattern.search(text)
            if match:
                found.append((rel, text[:match.start()].count("\n") + 1, what))
    if rel.startswith("android/") and rel.endswith(".xml") and "/res/drawable" in rel:
        match = ANDROID_PATTERN.search(text)
        if match:
            found.append((rel, text[:match.start()].count("\n") + 1,
                          "a drawable with path data that gen_icons.py did not write"))
    if rel.endswith(".xaml"):
        for pattern, what in XAML_PATTERNS:
            match = pattern.search(text)
            if match:
                found.append((rel, text[:match.start()].count("\n") + 1, what))
    if rel.startswith(WEB_DIRS) and rel.endswith((".html", ".js", ".svg")):
        match = WEB_PATTERN.search(text)
        if match:
            found.append((rel, text[:match.start()].count("\n") + 1,
                          "inline SVG path outside the generated sprite"))
    return found


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", help="only check files changed since this git ref")
    args = parser.parse_args()

    files = changed_files(args.base) if args.base else None
    if files is None:
        files = all_files()

    found = []
    for rel in files:
        # A diff against the base names files it deleted; there is nothing left to check.
        if not os.path.isfile(os.path.join(ROOT, rel)):
            continue
        found.extend(violations_in(rel))

    if not found:
        print("check_icons: no hand-drawn icons")
        return 0
    for rel, line, what in sorted(found):
        print("%s:%d: %s" % (rel, line, what))
    print("")
    print("check_icons: UI icons come from assets/icons/tabler via tools/gen_icons.py.")
    print("Add an icon there and regenerate; if this shape is genuinely not an icon, add it to")
    print("ALLOWED in tools/check_icons.py with the reason.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
