#!/usr/bin/env python3
"""Refuse hand-drawn icons in shell UI code.

Owner rule (2026-09-03): UI icons are never hand-drawn. Every shell takes them from one
open-source library -- Tabler Icons (MIT), vendored under assets/icons/tabler/ -- through
tools/gen_icons.py. A glyph typed out as a bezier in a view controller drifts from the other
three shells the moment anyone touches it, and nobody notices until the icons no longer match.

What this refuses:
  * UIBezierPath / CGPath / CGContextAddCurve glyph drawing in iOS and iOS-kiosk view files
  * <path android:pathData> in an Android drawable that gen_icons.py did not write
  * Path Data= or <Geometry> literals in XAML outside the generated Icons.xaml
  * inline <svg><path d=...> in webui outside the generated sprite

Shapes that are not icons -- a progress ring, a waveform, a slide-to-trigger track -- are real
and are listed in ALLOWED below, with the reason. Add to that list deliberately, not to make a
red build go away.

  python3 tools/check_icons.py            check the whole tree
  python3 tools/check_icons.py --base REF  check only files changed since REF
"""

import argparse
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Paths that legitimately draw a shape that is not an icon. Each entry is (path, reason).
ALLOWED = [
    ("win/DoorbellApp/Resources/Icons.xaml", "the generated Tabler geometry dictionary"),
    ("webui/icons/tabler-sprite.svg", "the generated Tabler sprite"),
    ("webui/admin/index.html", "carries the generated sprite between its markers"),
    ("android/app/src/main/res/drawable/banner_tv.xml",
     "the Android TV launcher banner: artwork with a title, not a UI icon"),
]

GENERATED_MARKER = "Generated by tools/gen_icons.py"

IOS_PATTERNS = [
    (re.compile(r"\bUIBezierPath\b"), "UIBezierPath glyph drawing"),
    (re.compile(r"\bCGPathAdd(?:Curve|QuadCurve|Arc)\w*\b"), "CGPath glyph drawing"),
    (re.compile(r"\bCGContextAdd(?:Curve|QuadCurve|Arc)\w*\b"), "CGContext glyph drawing"),
    (re.compile(r"\bPath\s*\{"), "SwiftUI Path glyph drawing"),
]
ANDROID_PATTERN = re.compile(r"<path[^>]*android:pathData")
XAML_PATTERNS = [
    (re.compile(r"\bData\s*=\s*\"[MmLlCcQqAaZzHhVv][\s\d.,-]"), "inline XAML path geometry"),
    (re.compile(r"<(?:Path|Stream)?Geometry\b"), "inline XAML geometry"),
]
WEB_PATTERN = re.compile(r"<svg\b[^>]*>.*?<path\b[^>]*\bd\s*=", re.S)

IOS_DIRS = ("ios/", "ios-kiosk/", "ios-legacy/")
WEB_DIRS = ("webui/",)


def allowed(rel):
    for path, _reason in ALLOWED:
        if rel == path or rel.startswith(path.rstrip("/") + "/"):
            return True
    return False


def is_view_file(rel):
    if not rel.startswith(IOS_DIRS):
        return False
    return rel.endswith((".m", ".mm", ".swift", ".h"))


def changed_files(base):
    try:
        out = subprocess.check_output(["git", "diff", "--name-only", base + "...HEAD"],
                                      cwd=ROOT, stderr=subprocess.DEVNULL)
    except (subprocess.CalledProcessError, OSError):
        return None
    return [line for line in out.decode("utf-8").splitlines() if line]


def all_files():
    out = subprocess.check_output(["git", "ls-files"], cwd=ROOT)
    return [line for line in out.decode("utf-8").splitlines() if line]


def read(rel):
    path = os.path.join(ROOT, rel)
    if not os.path.isfile(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read()
    except (UnicodeDecodeError, OSError):
        return None


def violations_in(rel):
    if allowed(rel):
        return []
    text = read(rel)
    if text is None:
        return []
    if GENERATED_MARKER in text:
        return []
    found = []
    if is_view_file(rel):
        for pattern, what in IOS_PATTERNS:
            match = pattern.search(text)
            if match:
                found.append((rel, text[:match.start()].count("\n") + 1, what))
    if rel.startswith("android/") and rel.endswith(".xml") and "/res/drawable" in rel:
        match = ANDROID_PATTERN.search(text)
        if match:
            found.append((rel, text[:match.start()].count("\n") + 1,
                          "a drawable with path data that gen_icons.py did not write"))
    if rel.endswith(".xaml"):
        for pattern, what in XAML_PATTERNS:
            match = pattern.search(text)
            if match:
                found.append((rel, text[:match.start()].count("\n") + 1, what))
    if rel.startswith(WEB_DIRS) and rel.endswith((".html", ".js", ".svg")):
        match = WEB_PATTERN.search(text)
        if match:
            found.append((rel, text[:match.start()].count("\n") + 1,
                          "inline SVG path outside the generated sprite"))
    return found


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", help="only check files changed since this git ref")
    args = parser.parse_args()

    files = changed_files(args.base) if args.base else None
    if files is None:
        files = all_files()

    found = []
    for rel in files:
        found.extend(violations_in(rel))

    if not found:
        print("check_icons: no hand-drawn icons")
        return 0
    for rel, line, what in sorted(found):
        print("%s:%d: %s" % (rel, line, what))
    print("")
    print("check_icons: UI icons come from assets/icons/tabler via tools/gen_icons.py.")
    print("Add an icon there and regenerate; if this shape is genuinely not an icon, add it to")
    print("ALLOWED in tools/check_icons.py with the reason.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
