#!/usr/bin/env python3
"""Embed webui assets and i18n locales generated from strings.yaml in C++ source.

Usage: embed_webui.py <output.cpp>
Mappings:
    webui/admin/index.html  → /admin/
    webui/admin/<f>         → /admin/<f>
    webui/panel/<name>.html → /panel/<name>
    webui/panel/<f>         → /panel/<f>   (CSS, JavaScript, and other assets)
    webui/panel/<dir>/<f>   → /panel/<dir>/<f>   (one directory level, such as vendor/)
    (strings.yaml)          → /locale/{ja,en,zh}.json
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_i18n  # noqa: E402  Reuse the dependency-free parser.

ROOT = gen_i18n.ROOT
CTYPES = {
    ".html": "text/html; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".mp3": "audio/mpeg",
    ".wav": "audio/wav",
    ".ico": "image/x-icon",
}


def collect():
    assets = []  # (url_path, content_type, bytes)
    for sub in ("admin", "panel"):
        base = os.path.join(ROOT, "webui", sub)
        if not os.path.isdir(base):
            continue
        for fn in sorted(os.listdir(base)):
            full = os.path.join(base, fn)
            if os.path.isdir(full) and sub == "panel":
                # Preserve paths for one level of subdirectories such as vendor/.
                for fn2 in sorted(os.listdir(full)):
                    full2 = os.path.join(full, fn2)
                    if not os.path.isfile(full2):
                        continue
                    ext2 = os.path.splitext(fn2)[1].lower()
                    with open(full2, "rb") as f:
                        data = f.read()
                    assets.append((f"/panel/{fn}/{fn2}",
                                   CTYPES.get(ext2, "application/octet-stream"), data))
                continue
            if not os.path.isfile(full):
                continue
            ext = os.path.splitext(fn)[1].lower()
            ctype = CTYPES.get(ext, "application/octet-stream")
            with open(full, "rb") as f:
                data = f.read()
            if sub == "admin" and fn == "index.html":
                url = "/admin/"
            elif sub == "panel" and ext == ".html":
                url = "/panel/" + os.path.splitext(fn)[0]
            else:
                url = f"/{sub}/{fn}"
            assets.append((url, ctype, data))
    # Built-in sounds are shared by every client. Keep the localized school-chime filename on
    # disk while exposing it through a stable ASCII preset URL.
    audio_files = {
        "outdoor_call_alert.mp3": "outdoor_call_alert.mp3",
        "button_click.mp3": "button_click.mp3",
        "\u5b66\u6821\u306e\u30c1\u30e3\u30a4\u30e0.mp3": "school_chime.mp3",
        "indoor_update.mp3": "indoor_update.mp3",
        "title_display.mp3": "title_display.mp3",
    }
    audio_base = os.path.join(ROOT, "assets", "audio")
    for filename, url_name in audio_files.items():
        with open(os.path.join(audio_base, filename), "rb") as f:
            assets.append((f"/audio/{url_name}", CTYPES[".mp3"], f.read()))
    # Generate locales directly from strings.yaml without relying on source-tree artifacts.
    entries = gen_i18n.parse(gen_i18n.SRC)
    for lang in gen_i18n.LANGS:
        data = {k: gen_i18n.text(entries, k, lang) for k in sorted(entries)}
        blob = json.dumps(data, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
        assets.append((f"/locale/{lang}.json", CTYPES[".json"], blob))
    return assets


def emit(assets, out_path):
    lines = [
        "// Generated by tools/embed_webui.py. Do not edit.",
        '#include "httpd/webui_assets.h"',
        "namespace db {",
    ]
    for i, (_, _, data) in enumerate(assets):
        body = ",".join(str(b) for b in data)
        lines.append(f"static const unsigned char a{i}[] = {{{body}}};")
    lines.append("static const WebAsset kAssets[] = {")
    for i, (url, ctype, data) in enumerate(assets):
        lines.append(f'  {{"{url}", "{ctype}", a{i}, {len(data)}}},')
    lines.append("};")
    lines.append("const WebAsset* webuiAssets(size_t* count) {")
    lines.append(f"  *count = {len(assets)};")
    lines.append("  return kAssets;")
    lines.append("}")
    lines.append("}  // namespace db")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    total = sum(len(d) for _, _, d in assets)
    print(f"embed_webui: {len(assets)} assets, {total} bytes -> {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: embed_webui.py <out.cpp>")
    emit(collect(), sys.argv[1])
