#!/usr/bin/env python3
"""Generate every shell's icon assets from the vendored Tabler outline SVGs.

Owner rule: UI icons are never hand-drawn. One open-source library -- Tabler Icons (MIT), the
outline set -- is vendored under assets/icons/tabler/ and every platform's icons are generated
from those files, so a glyph cannot drift between the Android drawable, the iOS asset, the
Windows geometry and the web sprite.

Outputs:
  android/app/src/main/res/drawable/ic_tabler_<name>.xml   VectorDrawable, stroked
  ios/Doorbell/Assets.xcassets/Tabler<Name>.imageset/      single-scale vector PDF
  ios-kiosk/resources/icons/tabler_<name>[@2x].png         raster for iOS 5 (needs Pillow)
  win/DoorbellApp/Resources/Icons.xaml                     Geometry resource dictionary
  webui/icons/tabler-sprite.svg                            standalone sprite
  webui/admin/index.html                                   the sprite, inlined between markers

Android pathData and the XAML mini-language both take SVG path syntax unchanged, so those two
keep the upstream geometry byte for byte. The PDF and PNG outputs need curves and arcs turned
into line segments first; tools/svg_path.py does that.

  python3 tools/gen_icons.py            regenerate
  python3 tools/gen_icons.py --check    fail if anything is out of date (never rasterises)
"""

import argparse
import hashlib
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import svg_path  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE_DIR = os.path.join(ROOT, "assets", "icons", "tabler")
MANIFEST = os.path.join(SOURCE_DIR, "manifest.json")

BANNER = "Generated by tools/gen_icons.py from assets/icons/tabler; do not edit."
STROKE_WIDTH = "2"
VIEWBOX = 24.0

SPRITE_BEGIN = "<!-- BEGIN generated icon sprite (tools/gen_icons.py); do not edit by hand -->"
SPRITE_END = "<!-- END generated icon sprite -->"

_PATH_D = re.compile(r'<path[^>]*\sd="([^"]+)"', re.S)


def icon_names():
    names = []
    for entry in sorted(os.listdir(SOURCE_DIR)):
        if entry.endswith(".svg"):
            names.append(entry[:-4])
    return names


def read_source(name):
    with open(os.path.join(SOURCE_DIR, name + ".svg"), "r", encoding="utf-8") as handle:
        return handle.read()


def path_data(text):
    """Every <path d> in the file, joined. Each starts with M, so one string is equivalent."""
    parts = [" ".join(match.split()) for match in _PATH_D.findall(text)]
    if not parts:
        raise SystemExit("no <path d> in an icon source; the vendored file is not a Tabler icon")
    return " ".join(parts)


def camel(name):
    return "".join(part.capitalize() for part in re.split(r"[-_]", name))


def sha256_text(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_file(path):
    if not os.path.exists(path):
        return ""
    with open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


# ---------------------------------------------------------------- Android

def android_xml(name, data):
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- " + BANNER + " -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp"\n'
        '    android:height="24dp"\n'
        '    android:viewportWidth="24"\n'
        '    android:viewportHeight="24"\n'
        '    android:tint="?attr/colorControlNormal">\n'
        "    <path\n"
        '        android:pathData="' + data + '"\n'
        '        android:strokeColor="#FF000000"\n'
        '        android:strokeWidth="' + STROKE_WIDTH + '"\n'
        '        android:strokeLineCap="round"\n'
        '        android:strokeLineJoin="round" />\n'
        "</vector>\n")


# ---------------------------------------------------------------- Windows

def xaml_dictionary(icons):
    lines = ['<?xml version="1.0" encoding="utf-8"?>',
             "<!-- " + BANNER + " -->",
             "<!-- Geometry only: a Path sets Stroke, StrokeThickness 2, and round caps and",
             "     joins, so one dictionary serves every foreground colour. -->",
             '<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
             '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">']
    for name, data in icons:
        lines.append('  <Geometry x:Key="Icon' + camel(name) + '">' + data + "</Geometry>")
    lines.append("</ResourceDictionary>")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- web sprite

def sprite_symbols(icons):
    out = []
    for name, data in icons:
        out.append(
            '<symbol id="i-' + name + '" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
            'stroke-width="' + STROKE_WIDTH + '" stroke-linecap="round" stroke-linejoin="round">'
            '<path d="' + data + '"/></symbol>')
    return "".join(out)


def sprite_svg(icons):
    return ('<!-- ' + BANNER + ' -->\n'
            '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">'
            + sprite_symbols(icons) + "</svg>\n")


def inline_sprite(html, icons):
    block = (SPRITE_BEGIN + "\n"
             '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">'
             + sprite_symbols(icons) + "</svg>\n" + SPRITE_END)
    start = html.find(SPRITE_BEGIN)
    end = html.find(SPRITE_END)
    if start < 0 or end < 0:
        raise SystemExit("webui/admin/index.html has no generated icon sprite markers")
    return html[:start] + block + html[end + len(SPRITE_END):]


# ---------------------------------------------------------------- iOS PDF

def pdf_bytes(name, data):
    """A one-page vector PDF, 24x24 points, stroked -- what an .imageset preserves as vector."""
    commands = []
    for _closed, points in svg_path.flatten(data):
        if not points:
            continue
        # PDF's origin is bottom-left; SVG's is top-left.
        commands.append("%.4f %.4f m" % (points[0][0], VIEWBOX - points[0][1]))
        for x, y in points[1:]:
            commands.append("%.4f %.4f l" % (x, VIEWBOX - y))
        if _closed:
            commands.append("h")
        commands.append("S")
    stream = ("0 0 0 RG\n" + STROKE_WIDTH + " w\n1 J\n1 j\n" + "\n".join(commands) + "\n")
    stream_bytes = stream.encode("ascii")

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 24 24] /Contents 4 0 R "
        b"/Resources << >> >>",
        b"<< /Length " + str(len(stream_bytes)).encode("ascii") + b" >>\nstream\n"
        + stream_bytes + b"endstream",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for index, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += str(index).encode("ascii") + b" 0 obj\n" + body + b"\nendobj\n"
    xref = len(out)
    out += b"xref\n0 " + str(len(objects) + 1).encode("ascii") + b"\n"
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += ("%010d 00000 n \n" % offset).encode("ascii")
    out += (b"trailer\n<< /Size " + str(len(objects) + 1).encode("ascii")
            + b" /Root 1 0 R >>\nstartxref\n" + str(xref).encode("ascii") + b"\n%%EOF\n")
    return bytes(out)


def imageset_contents():
    return json.dumps({
        "images": [{"idiom": "universal", "filename": "icon.pdf"}],
        "info": {"version": 1, "author": "tools/gen_icons.py"},
        "properties": {"preserves-vector-representation": True, "template-rendering-intent":
                       "template"},
    }, indent=2, sort_keys=True) + "\n"


# ---------------------------------------------------------------- kiosk PNG

def render_png(data, size, supersample=4):
    """Raster for iOS 5, which has no vector assets. Needs Pillow; returns None without it."""
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        return None
    scale = size * supersample / VIEWBOX
    width = int(round(STROKE_WIDTH_FLOAT * scale))
    image = Image.new("RGBA", (size * supersample, size * supersample), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    radius = width / 2.0
    for _closed, points in svg_path.flatten(data, curve_steps=24):
        scaled = [(x * scale, y * scale) for x, y in points]
        if _closed and scaled[0] != scaled[-1]:
            scaled.append(scaled[0])
        if len(scaled) == 1:
            scaled.append((scaled[0][0] + 0.01, scaled[0][1]))
        draw.line(scaled, fill=(0, 0, 0, 255), width=width)
        # Pillow draws mitred joins only, so round them off by hand at every vertex.
        for x, y in scaled:
            draw.ellipse([x - radius, y - radius, x + radius, y + radius], fill=(0, 0, 0, 255))
    return image.resize((size, size), Image.LANCZOS)


STROKE_WIDTH_FLOAT = float(STROKE_WIDTH)


# ---------------------------------------------------------------- driver

def write(path, content, results, binary=False):
    directory = os.path.dirname(path)
    if directory and not os.path.isdir(directory):
        os.makedirs(directory)
    mode = "wb" if binary else "w"
    existing = None
    if os.path.exists(path):
        with open(path, "rb") as handle:
            existing = handle.read()
        if not binary:
            existing = existing.decode("utf-8")
    if existing == content:
        results["current"].append(path)
        return
    with open(path, mode, **({} if binary else {"encoding": "utf-8"})) as handle:
        handle.write(content)
    results["written"].append(path)


def stale(path, content, results, binary=False):
    if not os.path.exists(path):
        results["missing"].append(path)
        return
    with open(path, "rb") as handle:
        existing = handle.read()
    if not binary:
        existing = existing.decode("utf-8")
    if existing != content:
        results["stale"].append(path)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the generated files are current; do not write anything")
    args = parser.parse_args()

    names = icon_names()
    if not names:
        raise SystemExit("no vendored icons in " + SOURCE_DIR)
    icons = [(name, path_data(read_source(name))) for name in names]

    results = {"written": [], "current": [], "stale": [], "missing": []}
    act = stale if args.check else write

    for name, data in icons:
        act(os.path.join(ROOT, "android/app/src/main/res/drawable",
                         "ic_tabler_" + name.replace("-", "_") + ".xml"),
            android_xml(name, data), results)
        imageset = os.path.join(ROOT, "ios/Doorbell/Assets.xcassets",
                                "Tabler" + camel(name) + ".imageset")
        act(os.path.join(imageset, "Contents.json"), imageset_contents(), results)
        act(os.path.join(imageset, "icon.pdf"), pdf_bytes(name, data), results, binary=True)

    act(os.path.join(ROOT, "win/DoorbellApp/Resources/Icons.xaml"),
        xaml_dictionary(icons), results)
    act(os.path.join(ROOT, "webui/icons/tabler-sprite.svg"), sprite_svg(icons), results)

    index_path = os.path.join(ROOT, "webui/admin/index.html")
    with open(index_path, "r", encoding="utf-8") as handle:
        html = handle.read()
    act(index_path, inline_sprite(html, icons), results)

    # The kiosk PNGs are the one output that needs a rasteriser, so --check compares recorded
    # hashes instead of re-rendering: a CI runner without Pillow can still verify currency.
    manifest = {"source": {name: sha256_text(read_source(name)) for name in names}, "png": {}}
    previous = {}
    if os.path.exists(MANIFEST):
        with open(MANIFEST, "r", encoding="utf-8") as handle:
            previous = json.load(handle)
    kiosk_dir = os.path.join(ROOT, "ios-kiosk/resources/icons")
    png_ok = True
    for name, data in icons:
        for suffix, size in (("", 24), ("@2x", 48)):
            path = os.path.join(kiosk_dir, "tabler_" + name.replace("-", "_") + suffix + ".png")
            key = os.path.relpath(path, ROOT)
            if args.check:
                digest = sha256_file(path)
                if not digest:
                    results["missing"].append(path)
                elif previous.get("png", {}).get(key) != digest:
                    results["stale"].append(path)
                manifest["png"][key] = previous.get("png", {}).get(key, "")
                continue
            image = render_png(data, size)
            if image is None:
                png_ok = False
                manifest["png"][key] = previous.get("png", {}).get(key, "")
                continue
            if not os.path.isdir(kiosk_dir):
                os.makedirs(kiosk_dir)
            image.save(path, "PNG", optimize=True)
            manifest["png"][key] = sha256_file(path)
            results["written"].append(path)

    manifest_text = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    if args.check:
        if previous.get("source") != manifest["source"]:
            results["stale"].append(MANIFEST)
    else:
        write(MANIFEST, manifest_text, results)

    if args.check:
        problems = results["stale"] + results["missing"]
        if problems:
            for path in sorted(problems):
                print("gen_icons: out of date: " + os.path.relpath(path, ROOT))
            print("gen_icons: run python3 tools/gen_icons.py")
            return 1
        print("gen_icons: %d icons, all generated files are current" % len(icons))
        return 0

    if not png_ok:
        print("gen_icons: Pillow is not installed, so the iOS 5 kiosk PNGs were left alone")
    print("gen_icons: %d icons, %d files written, %d already current"
          % (len(icons), len(results["written"]), len(results["current"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
