#!/usr/bin/env python3
"""i18n/strings.yaml (制限付き 1 行形式) から各プラットフォームの文言資産を生成する。

依存なし (PyYAML 不使用 — 旧ビルド機対策)。形式:
    key.path: { ja: "…", en: "…", zh: "…" }

出力:
    webui/locale/{ja,en,zh}.json                 ({name} のまま)
    android/app/src/main/res/values[-ja|-zh]/strings.xml  (%1$s… 出現順)
    ios/Doorbell/{ja,en,zh}.lproj/Localizable.strings     (%@)
    win/DoorbellApp/Strings.{ja,en,zh}.resx               ({0}…)

検証: 言語間プレースホルダ不一致 = エラー (exit 1)。訳漏れ = 警告 + ja へフォールバック。
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "i18n", "strings.yaml")
LANGS = ["ja", "en", "zh"]
BASE = "ja"

LINE_RE = re.compile(r'^([A-Za-z0-9_.]+):\s*\{\s*(.*)\s*\}\s*$')
PAIR_RE = re.compile(r'(\w+):\s*"((?:[^"\\]|\\.)*)"')
PH_RE = re.compile(r'\{(\w+)\}')


def parse(path):
    entries = {}  # key -> {lang: text}
    with open(path, encoding="utf-8") as f:
        for ln, raw in enumerate(f, 1):
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            m = LINE_RE.match(line)
            if not m:
                sys.exit(f"{path}:{ln}: 解析不能な行: {line!r}")
            key, body = m.group(1), m.group(2)
            langs = {}
            for lm in PAIR_RE.finditer(body):
                langs[lm.group(1)] = lm.group(2).replace('\\"', '"').replace("\\\\", "\\")
            if BASE not in langs:
                sys.exit(f"{path}:{ln}: {key} に原文 ({BASE}) がありません")
            entries[key] = langs
    return entries


def validate(entries):
    errors = 0
    for key, langs in entries.items():
        base_ph = sorted(PH_RE.findall(langs[BASE]))
        for lang in LANGS:
            if lang not in langs:
                print(f"warn: {key}: {lang} 訳なし → {BASE} にフォールバック", file=sys.stderr)
                continue
            if sorted(PH_RE.findall(langs[lang])) != base_ph:
                print(f"error: {key}: プレースホルダ不一致 ({lang})", file=sys.stderr)
                errors += 1
    if errors:
        sys.exit(1)


def text(entries, key, lang):
    return entries[key].get(lang, entries[key][BASE])


def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print(f"  {os.path.relpath(path, ROOT)}")


def xml_escape(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;").replace("'", "\\'"))


def gen_web(entries):
    for lang in LANGS:
        data = {k: text(entries, k, lang) for k in sorted(entries)}
        write(os.path.join(ROOT, "webui", "locale", f"{lang}.json"),
              json.dumps(data, ensure_ascii=False, indent=1) + "\n")


def to_android(s):
    # {name} → %1$s (出現順)
    order = []

    def rep(m):
        name = m.group(1)
        if name not in order:
            order.append(name)
        return f"%{order.index(name) + 1}$s"
    return PH_RE.sub(rep, s)


def gen_android(entries):
    for lang in LANGS:
        suffix = "" if lang == "en" else f"-{lang}"  # values/ は既定 (en), values-ja, values-zh
        lines = ['<?xml version="1.0" encoding="utf-8"?>', "<resources>"]
        for k in sorted(entries):
            name = k.replace(".", "_")
            lines.append(f'    <string name="{name}">{xml_escape(to_android(text(entries, k, lang)))}</string>')
        lines.append("</resources>\n")
        write(os.path.join(ROOT, "android", "app", "src", "main", "res",
                           f"values{suffix}", "strings.xml"), "\n".join(lines))


def gen_ios(entries):
    for lang in LANGS:
        lines = ["/* generated by tools/gen_i18n.py — 編集禁止 */"]
        for k in sorted(entries):
            v = PH_RE.sub("%@", text(entries, k, lang))
            v = v.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'"{k}" = "{v}";')
        write(os.path.join(ROOT, "ios", "Doorbell", f"{lang}.lproj",
                           "Localizable.strings"), "\n".join(lines) + "\n")


def to_dotnet(s):
    order = []

    def rep(m):
        name = m.group(1)
        if name not in order:
            order.append(name)
        return f"{{{order.index(name)}}}"
    return PH_RE.sub(rep, s)


RESX_HEAD = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""


def gen_win(entries):
    for lang in LANGS:
        # 既定リソース (Strings.resx) は ja — 主言語。他言語はカルチャ別。
        fname = "Strings.resx" if lang == "ja" else f"Strings.{lang}.resx"
        parts = [RESX_HEAD]
        for k in sorted(entries):
            name = k.replace(".", "_")
            v = xml_escape(to_dotnet(text(entries, k, lang))).replace("\\'", "'")
            parts.append(f'  <data name="{name}" xml:space="preserve"><value>{v}</value></data>\n')
        parts.append("</root>\n")
        write(os.path.join(ROOT, "win", "DoorbellApp", "Resources", fname), "".join(parts))


def main():
    entries = parse(SRC)
    validate(entries)
    print(f"gen_i18n: {len(entries)} keys → ")
    gen_web(entries)
    gen_android(entries)
    gen_ios(entries)
    gen_win(entries)


if __name__ == "__main__":
    main()
