"use strict";
const assert=require('node:assert/strict'), L=require('../admin/app.js');
const privateValue='SYNTHETIC-PRIVATE-VALUE';
const config={admin:{password_hash:{hash:privateValue}},settings:{keep:true,innocent:'A token is mentioned in documentation'},sip:{password:privateValue,password_ref:'secret:sip.restore'},integrations:{mqtt:{pass:privateValue,pass_ref:'secret:mqtt.pass'},telegram:{bot_token:privateValue}},web_push:{auth:privateValue,vapid:{private_key:privateValue,public_key:'public-fixture'}},custom:{url:'https://example.invalid/?token='+privateValue},panel:{token_generation:'a'.repeat(32),token_refs:['secret:panel.fixture']}};
const exported=L.configExportDocument(config,{id:'node-fixture',version:'1.2.3'});
assert.equal(exported.schema_version,2);assert.equal(exported.content_scope,'configuration_without_secrets_or_assets');
assert(!JSON.stringify(exported).includes(privateValue));assert.equal(exported.config.integrations.mqtt.pass_ref,'secret:mqtt.pass');
assert.equal(exported.config.settings.innocent,'A token is mentioned in documentation');assert.equal(exported.config.sip.password_ref,'secret:sip.restore');assert.equal(exported.config.web_push.vapid.public_key,'public-fixture');
assert.equal(exported.config.panel.token_generation,'a'.repeat(32));assert.deepEqual(exported.config.panel.token_refs,['secret:panel.fixture']);assert(exported.excluded_paths.length>=4);
const entries=Array.from({length:257},(_,n)=>({key:'import_fixture.leaf_'+n,value:n}));
const converted=L.configImportDocument(JSON.stringify({entries}),{settings:{keep:true}},false);
assert.equal(Object.keys(converted.config.import_fixture).length,257);assert(converted.config.settings.keep);
assert.deepEqual(L.configImportDocument('{"settings":{"new":1}}',{settings:{keep:true}},false).config,{settings:{keep:true,new:1}});
assert.deepEqual(L.configImportDocument('{"settings":{"new":1}}',{settings:{keep:true}},true).config,{settings:{new:1}});
assert.equal(L.configImportDocument(JSON.stringify(exported),{},false).schema_version,2);
for(const text of ['{"schema_version":99,"config":{}}','{"__proto__":{"polluted":true}}','{"entries":[{"key":"settings.__proto__.polluted","value":true}]}','{"a":1,"a":2}','{"nested":{"a":1,"a":2}}','{"nested":{"constructor":{}}}','{"entries":[{"key":"settings.a","value":1},{"key":"settings.a","value":2}]}']) assert.throws(()=>L.configImportDocument(text,{},false));
assert.throws(()=>L.configImportDocument(' '.repeat(4*1024*1024+1),{},false));
assert.equal({}.polluted,undefined);
console.log('Staged import conversion and safe export: PASS');
