"use strict";
async function runAdminImportTests(){
  const results=[],frame=document.getElementById('subject');let w,d,f;
  const assert=(v,m)=>{if(!v)throw Error(m);},sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const wait=async p=>{const until=Date.now()+5000;while(!p()){if(Date.now()>until)throw Error('Timed out waiting for UI');await sleep(15);}};
  const $=s=>d.querySelector(s),requests=action=>f.requests.filter(r=>r.url==='/api/config/import/'+action);
  async function fresh(){frame.src='/?case='+Math.random();await new Promise(r=>frame.onload=r);w=frame.contentWindow;d=w.document;f=w.adminImportFixture;await wait(()=>w.__DOORBELL_TEST_HOOKS.adminRuntime&&!$('#app').classList.contains('hidden')&&$('#nodeInfo').textContent.includes('import-fixture'));w.__DOORBELL_TEST_HOOKS.adminRuntime.switchTab('system');await wait(()=>$('#sysImport'));}
  async function prepare(value,replace=false){$('#sysImport').value=typeof value==='string'?value:JSON.stringify(value);$('#sysImportReplace').checked=replace;$('#sysImportBtn').click();await wait(()=>!$('#sysImportWorkflow').getAttribute('aria-busy')||$('#sysImportWorkflow').getAttribute('aria-busy')==='false');}
  async function preview(value,replace=false){await prepare(value,replace);await wait(()=>requests('preflight').length&&$('#sysImportWorkflow').getAttribute('aria-busy')==='false');}
  function commit(){assert($('#sysImportCommit').disabled,'Commit enabled without confirmation');$('#sysImportAck').click();$('#sysImportCommit').click();}
  async function test(id,body){try{await fresh();await body();results.push({id,status:'PASS'});}catch(e){results.push({id,status:'FAIL',message:e.message});}document.getElementById('result').textContent=JSON.stringify(results,null,2);}
  await test('257 legacy entries preview and commit through staged APIs',async()=>{
    await preview({entries:Array.from({length:257},(_,n)=>({key:'fixture.leaf_'+n,value:n}))});
    assert(Object.keys(f.stage.document.config.fixture).length===257,'Conversion lost entries');assert(f.stage.document.config.settings.keep==='existing','Default merge deleted existing values');
    assert(!f.requests.some(r=>r.url==='/api/config/commit'||r.url==='/api/config/import'),'Used an ordinary or legacy import route');commit();await wait(()=>$('#sysImportClear'));
    assert(requests('commit').length===1,'Multiple commits');assert($('#sysImportWorkflow').textContent.includes('this node'),'Local outcome absent');
    await wait(()=>$('#sysImportWorkflow').textContent.includes('1 online / 2'));assert($('#sysImportWorkflow').textContent.includes('has not been verified'),'Peer sync claimed');
  });
  await test('Full replacement explicitly previews deletions before confirmation',async()=>{await preview({settings:{new:1}},true);assert(!('keep' in f.stage.document.config.settings),'Replacement merged old field');assert($('#sysImportWorkflow').textContent.includes('/settings/keep'),'Deletion missing');assert(requests('commit').length===0,'Preview committed');});
  await test('Missing secret blocks commit and explains separate reprovisioning',async()=>{f.mode='missing-secret';await preview({integrations:{mqtt:{pass_ref:'secret:mqtt.restore'}}});assert(!$('#sysImportCommit'),'Missing secret accepted');assert($('#sysImportWorkflow').textContent.includes('secret:mqtt.restore')&&$('#sysImportWorkflow').textContent.includes('secure-storage'),'Reprovision guidance missing');$('#sysImportDiscard').click();await wait(()=>$('#sysImport'));});
  await test('Missing asset blocks commit and exposes upload recovery',async()=>{f.mode='missing-asset';await preview({settings:{asset:'fixture-asset'}});assert(!$('#sysImportCommit')&&$('#sysImportWorkflow').textContent.includes('Assets'),'Missing asset accepted');});
  await test('Preflight response must bind the exact staged digest',async()=>{f.mode='wrong-digest';await preview({settings:{new:1}});assert(!$('#sysImportCommit'),'Foreign preview enabled commit');});
  await test('Malformed and unsupported documents cannot create a stage',async()=>{for(const text of ['{"schema_version":99,"config":{}}','{"a":1,"a":2}','{"x":{"constructor":{}}}','{"x":{"__proto__":{"polluted":true}}}','{']){await prepare(text);assert(requests('stage').length===0,'Invalid document staged');}assert(!({}).polluted,'Prototype polluted');});
  await test('Oversized input is rejected locally without a request',async()=>{await prepare(' '.repeat(4*1024*1024+1));assert(requests('stage').length===0,'Oversized document staged');});
  await test('A stale revision never automatically restages or commits',async()=>{f.mode='stage-conflict';await prepare({settings:{new:1}});assert(requests('stage').length===1&&requests('preflight').length===0&&requests('commit').length===0,'Conflict auto retried');});
  await test('Lost commit response queries the original operation only',async()=>{f.mode='lost-reply';await preview({settings:{new:1}});commit();await wait(()=>f.held);const request=JSON.parse(requests('commit')[0].body);assert(sessionStorage.getItem('doorbell.admin.import.v2').includes(request.operation_id),'Handle not persisted before response');f.timeoutHeld();await wait(()=>!$('#sysImportQuery').disabled);$('#sysImportQuery').click();await wait(()=>$('#sysImportClear'));assert(JSON.stringify(JSON.parse(requests('query')[0].body))===JSON.stringify(request),'Query changed operation');assert(requests('stage').length===1&&requests('commit').length===1,'Lost reply caused another import');});
  await test('Unknown query remains unknown without automatic import',async()=>{f.mode='query-missing';await preview({settings:{new:1}});commit();await wait(()=>f.held);f.timeoutHeld();$('#sysImportQuery').click();await wait(()=>!$('#sysImportQuery').disabled);assert(!$('#sysImportClear')&&requests('commit').length===1&&requests('stage').length===1,'Unknown query claimed success or retried');});
  await test('Repeated confirmation cannot submit a second operation',async()=>{f.mode='lost-reply';await preview({settings:{new:1}});const button=$('#sysImportCommit');$('#sysImportAck').click();button.click();button.click();await wait(()=>f.held);assert(requests('commit').length===1,'Repeated activation created duplicate');f.timeoutHeld();});
  await test('401 discards sensitive input and keeps only recovery handle',async()=>{f.mode='auth-loss';await preview({settings:{new:1}});commit();await wait(()=>f.held);const old=f.held;f.failHeld(401,{error_code:'unauthorized'});await wait(()=>!$('#login').classList.contains('hidden'));assert(!$('#sysImport')||$('#sysImport').value==='','Sensitive text retained');const stored=JSON.parse(sessionStorage.getItem('doorbell.admin.import.v2'));assert(Object.keys(stored).sort().join(',')==='digest,node_id,operation_id,schema_version,stage_token','Recovery stores extra content');$('#pw').value='fixture-only';$('#loginBtn').click();await wait(()=>!$('#app').classList.contains('hidden'));w.__DOORBELL_TEST_HOOKS.adminRuntime.switchTab('system');await wait(()=>$('#sysImportQuery'));old.respond(200,{ok:true});assert(!$('#sysImportClear'),'Stale response claimed success');});
  await test('Reload recovery offers query without creating a stage',async()=>{sessionStorage.setItem('doorbell.admin.import.v2',JSON.stringify({schema_version:2,stage_token:'a'.repeat(32),digest:'b'.repeat(64),operation_id:'c'.repeat(32),node_id:'import-fixture'}));frame.src='/?recover=1';await new Promise(r=>frame.onload=r);w=frame.contentWindow;d=w.document;f=w.adminImportFixture;await wait(()=>w.__DOORBELL_TEST_HOOKS.adminRuntime&&!$('#app').classList.contains('hidden')&&$('#nodeInfo').textContent.includes('import-fixture'));w.__DOORBELL_TEST_HOOKS.adminRuntime.switchTab('system');await wait(()=>$('#sysImportWorkflow'));assert($('#sysImportQuery')&&!$('#sysImportBtn'),'Recovery offered another import');assert(requests('stage').length===0,'Reload staged another import');});
  await test('Export excludes synthetic passwords tokens private keys and credential URLs',async()=>{f.config={sip:{password:'SYNTHETIC-PRIVATE',password_ref:'secret:sip.restore'},integrations:{token:'SYNTHETIC-PRIVATE'},web_push:{vapid:{private_key:'SYNTHETIC-PRIVATE',public_key:'fixture-public'}},settings:{url:'https://user:SYNTHETIC-PRIVATE@example.invalid/?token=SYNTHETIC-PRIVATE',innocent:'Keep token documentation'}};w.__DOORBELL_TEST_HOOKS.adminRuntime.switchTab('doors');await sleep(30);w.__DOORBELL_TEST_HOOKS.adminRuntime.switchTab('system');/* The background snapshot is refreshed by preparation, not tab selection. */await prepare('{');w.__DOORBELL_TEST_HOOKS.adminRuntime.recover();await sleep(5200);$('#sysExport').click();const text=await f.exportBlob.text(),doc=JSON.parse(text);assert(!text.includes('SYNTHETIC-PRIVATE'),'Secret leaked');assert(doc.config.sip.password_ref==='secret:sip.restore','Secret reference lost');assert(doc.config.settings.innocent==='Keep token documentation','Unrelated value altered');assert(doc.schema_version===2&&doc.content_scope==='configuration_without_secrets_or_assets'&&doc.excluded_paths.length>=4,'Export scope absent');});
  await test('Redacted export metadata stays visible before any commit',async()=>{await preview({schema_version:2,format:'doorbell-config',excluded_paths:['sip.password'],config:{sip:{password_ref:'secret:sip.restore'}}});assert($('#sysImportWorkflow').textContent.includes('sip.password')&&$('#sysImportWorkflow').textContent.includes('restore them separately'),'Export omissions hidden');assert(!JSON.stringify(f.stage.document.config).includes('[redacted]'),'A redacted placeholder was submitted');});
  await test('Unknown result requires explicit acknowledgement before another preview',async()=>{f.mode='query-missing';await preview({settings:{new:1}});commit();await wait(()=>f.held);const old=JSON.parse(requests('commit')[0].body);f.timeoutHeld();$('#sysImportQuery').click();await wait(()=>$('#sysImportNewPreview'));assert($('#sysImportNewPreview').disabled,'New preview implicitly enabled');$('#sysImportUnknownAck').click();$('#sysImportNewPreview').click();assert($('#sysImportBtn')&&$('#sysImportWorkflow').textContent.includes(old.operation_id),'Previous reference lost');assert(requests('stage').length===1&&requests('commit').length===1,'Acknowledgement sent another import');});
  await test('Authentication expiry clears an unsubmitted sensitive file',async()=>{$('#sysImport').value='{"settings":{"private_fixture":"SYNTHETIC-PRIVATE"}}';w.__DOORBELL_TEST_HOOKS.adminRuntime.stop();assert($('#sysImport').value==='','Unsubmitted sensitive DOM retained');});
  return results;
}
